server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://awseb-e-brdma433y3-stack-awsebrdsdatabase-dg2fzfemlgtl.cvxkfytfaftd.us-east-1.rds.amazonaws.com:3306/Mockproject
    username: root
    password: admin123
  jpa:
    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 322441792167-4rhmvhv3pqd9qponblv8je8gh00379jj.apps.googleusercontent.com
            clientSecret: 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
          # facebook:
          #   client-id: 2450541145086212
          #   client-secret: de9d44d5ab9894232e2a6b8a6b6daaf0
